/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AmasteciaAdminRouteImport } from './routes/amastecia-admin'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkIdentRouteImport } from './routes/work.$ident'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AmasteciaAdminRoute = AmasteciaAdminRouteImport.update({
  id: '/amastecia-admin',
  path: '/amastecia-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIdentRoute = WorkIdentRouteImport.update({
  id: '/$ident',
  path: '/$ident',
  getParentRoute: () => WorkRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/amastecia-admin': typeof AmasteciaAdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/shop': typeof ShopRoute
  '/work': typeof WorkRouteWithChildren
  '/work/$ident': typeof WorkIdentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/amastecia-admin': typeof AmasteciaAdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/shop': typeof ShopRoute
  '/work': typeof WorkRouteWithChildren
  '/work/$ident': typeof WorkIdentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/amastecia-admin': typeof AmasteciaAdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/shop': typeof ShopRoute
  '/work': typeof WorkRouteWithChildren
  '/work/$ident': typeof WorkIdentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/amastecia-admin'
    | '/auth'
    | '/contact'
    | '/shop'
    | '/work'
    | '/work/$ident'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/amastecia-admin'
    | '/auth'
    | '/contact'
    | '/shop'
    | '/work'
    | '/work/$ident'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/amastecia-admin'
    | '/auth'
    | '/contact'
    | '/shop'
    | '/work'
    | '/work/$ident'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AmasteciaAdminRoute: typeof AmasteciaAdminRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  ShopRoute: typeof ShopRoute
  WorkRoute: typeof WorkRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amastecia-admin': {
      id: '/amastecia-admin'
      path: '/amastecia-admin'
      fullPath: '/amastecia-admin'
      preLoaderRoute: typeof AmasteciaAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$ident': {
      id: '/work/$ident'
      path: '/$ident'
      fullPath: '/work/$ident'
      preLoaderRoute: typeof WorkIdentRouteImport
      parentRoute: typeof WorkRoute
    }
  }
}

interface WorkRouteChildren {
  WorkIdentRoute: typeof WorkIdentRoute
}

const WorkRouteChildren: WorkRouteChildren = {
  WorkIdentRoute: WorkIdentRoute,
}

const WorkRouteWithChildren = WorkRoute._addFileChildren(WorkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AmasteciaAdminRoute: AmasteciaAdminRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  ShopRoute: ShopRoute,
  WorkRoute: WorkRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
